const ML_SERVICE_URL = process.env.ML_SERVICE_URL || "http://localhost:5001";                                                                                                                                                               
const TIMEOUT_MS = 5000;                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            
async function post(path, body) {                                                                                                                                                                                                           
  const res = await fetch(`${ML_SERVICE_URL}${path}`, {                                                                                                                                                                                     
    method: "POST",                                                                                                                                                                                                                         
    headers: { "Content-Type": "application/json" },                                                                                                                                                                                        
    body: JSON.stringify(body),                                                                                                                                                                                                             
    signal: AbortSignal.timeout(TIMEOUT_MS),                                                                                                                                                                                                
  });                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
  const data = await res.json().catch(() => ({}));                                                                                                                                                                                          
                                                                                                                                                                                                                                            
  if (!res.ok) {                                                                                                                                                                                                                            
    const err = new Error(data.error || `ML service error: ${res.status}`);                                                                                                                                                                 
    err.status = res.status;                                                                                                                                                                                                                
    throw err;                                                                                                                                                                                                                              
  }                                                                                                                                                                                                                                         
  return data;                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
function estimatePrice({ postalCode, size, rooms, buildingYear, buildingType }) {                                                                                                                                                           
  return post("/predict", { postalCode, size, rooms, buildingYear, buildingType });                                                                                                                                                         
}                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
function predictGrowth({ postalCode }) {                                                                                                                                                                                                    
  return post("/predict-growth", { postalCode });                                                                                                                                                                                           
}                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
module.exports = { estimatePrice, predictGrowth };    