const { estimatePrice, predictGrowth } = require("../services/estimationService");                                                                                                                                                                  
                                                                                                                                                                                                                                            
const VALID_BUILDING_TYPES = new Set(["apartment",
    "detached-house",
    "semi-detached-house",
    "terraced-house"]);                                                                                                                                                                
                                                                                                                                                                                                                                            
async function getEstimate(req, res, next) {                                                                                                                                                                                                
  try {                                                                                                                                                                                                                                     
    const { postalCode, size, rooms, buildingYear, buildingType } = req.body;                                                                                                                                                               
                                                                                                                                                                                                                                            
    // --- validation ---                                                                                                                                                                                                                   
    if (postalCode == null || size == null || buildingYear == null || !buildingType) {                                                                                                                                                      
      return res.status(400).json({                                                                                                                                                                                                         
        error: "postalCode, size, buildingYear and buildingType are required",                                                                                                                                                              
      });                                                                                                                                                                                                                                   
    }
    if (postalCode.match(/\d\d\d\d\d/) == null) {                                                                                                                                                                                                               
      return res.status(400).json({ error: "invalid postalCode" });                                                                                                                                                                     
    }                                                                                                                                                                                                                                           
    if (!VALID_BUILDING_TYPES.has(buildingType)) {                                                                                                                                                                                          
      return res.status(400).json({                                                                                                                                                                                                         
        error: `buildingType must be one of: ${[...VALID_BUILDING_TYPES].join(", ")}`,                                                                                                                                                      
      });                                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                       
    if (typeof size !== "number" || size <= 0) {                                                                                                                                                                                            
      return res.status(400).json({ error: "size must be a positive number" });                                                                                                                                                             
    }                                                                                                                                                                                                                                       
    if (!Number.isInteger(buildingYear) || buildingYear < 1800 || buildingYear > 2026) {                                                                                                                                                    
      return res.status(400).json({ error: "buildingYear must be a valid year" });                                                                                                                                                          
    }                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
    const result = await estimatePrice({ postalCode, size, rooms, buildingYear, buildingType });                                                                                                                                            
    res.json(result);                                                                                                                                                                                                                       
  } catch (err) {                                                                                                                                                                                                                           
    next(err);                                                                                                                                                                                                                              
  }                                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
async function getGrowth(req, res, next) {                                                                                                                                                                                                  
  try {                                                                                                                                                                                                                                     
    const { postalCode } = req.body;                                                                                                                                                                                                        
                                                                                                                                                                                                                                            
    if (postalCode == null) {                                                                                                                                                                                                               
      return res.status(400).json({ error: "postalCode is required" });                                                                                                                                                                     
    }
    if (postalCode.match(/\d\d\d\d\d/) == null) {                                                                                                                                                                                                               
      return res.status(400).json({ error: "invalid postalCode" });                                                                                                                                                                     
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    const result = await predictGrowth({ postalCode });                                                                                                                                                                                     
    res.json(result);                                                                                                                                                                                                                       
  } catch (err) {                                                                                                                                                                                                                           
    next(err);                                                                                                                                                                                                                              
  }                                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
module.exports = { getEstimate, getGrowth };  