import house_image from "./src/assets/house1.jpg"

export const navLinks = [
    { id: 1, href: "/rent", text: "For Rent", footerText: "Rent a house" },
    { id: 2, href: "/buy", text: "Buy", footerText: "Buy a house" },
    { id: 3, href: "/sell", text: "Sell", footerText: "Sell a house" },
    { id: 4, href: "/contact", text: "Contact us", footerText: "Contact us" },
];

export const authLinks = [
    { id: 1, href: "/login", text: "Login" },
    { id: 2, href: "/register", text: "Register" },
];

export const properties = [
    {
        id: 1, ownerId: 1, title: "Modern apartment in Helsinki",
        description: "Bright two-bedroom apartment near the city centre.",
        listingType: "rent",
        propertyType: "residential",
        propertySubType: "apartment",
        price: 1250,
        currency: "EUR",
        city: "Helsinki",
        address: "Example Street 10",
        postalCode: "00100",
        rooms: 2,
        bedrooms: 1,
        bathrooms: 1,
        size: 55,
        features: {
            balcony: true,
            elevator: true,
            parking: true,
            furnished: true,
            petsAllowed: true,
            sauna: false,
        },
        rentalDetails: {
            availableFrom: "2026-10-01",
            deposit: 1250,
            minimumRentalPeriod: 12,
            additionalCosts: "Electricity and water are included.",
        },
        image: house_image,
        images: [
            {
                id: 1,
                url: "/images/property-001.jpg",
                description: "Living room",
                isMain: true,
            },
        ], status: "active",
    },
    // Possible values: "active", "inactive", "sold", "rented"   createdAt: "2026-09-06T12:00:00Z",   updatedAt: "2026-09-06T12:00:00Z",
    {
        id: 2,
        ownerId: 2,
        title: "Cozy studio apartment in Kallio",
        description: "Compact and stylish studio in a lively neighborhood close to cafes and public transport.",
        listingType: "rent",
        propertyType: "residential",
        propertySubType: "studio",
        price: 890,
        currency: "EUR",
        city: "Helsinki",
        address: "Fleminginkatu 22",
        postalCode: "00530",
        rooms: 1,
        bedrooms: 0,
        bathrooms: 1,
        size: 32,
        features: {
            balcony: false,
            elevator: true,
            parking: false,
            furnished: true,
            petsAllowed: false,
            sauna: false,
        },
        rentalDetails: {
            availableFrom: "2026-10-15",
            deposit: 890,
            minimumRentalPeriod: 6,
            additionalCosts: "Electricity is not included.",
        },
        image: house_image,
        images: [
            {
                id: 2,
                url: "/images/property-002.jpg",
                description: "Main living area",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T13:00:00Z",
        updatedAt: "2026-09-06T13:00:00Z",
    },

    {
        id: 3,
        ownerId: 3,
        title: "Spacious family home in Espoo",
        description: "Large family-friendly home with a private yard in a quiet residential area.",
        listingType: "sale",
        propertyType: "residential",
        propertySubType: "house",
        price: 425000,
        currency: "EUR",
        city: "Espoo",
        address: "Metsätie 15",
        postalCode: "02130",
        rooms: 5,
        bedrooms: 3,
        bathrooms: 2,
        size: 128,
        features: {
            balcony: true,
            elevator: false,
            parking: true,
            furnished: false,
            petsAllowed: true,
            sauna: true,
        },
        rentalDetails: {
            availableFrom: null,
            deposit: null,
            minimumRentalPeriod: null,
            additionalCosts: "Heating and maintenance costs apply.",
        },
        image: house_image,
        images: [
            {
                id: 3,
                url: "/images/property-003.jpg",
                description: "Exterior of the house",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T14:00:00Z",
        updatedAt: "2026-09-06T14:00:00Z",
    },

    {
        id: 4,
        ownerId: 4,
        title: "Bright one-bedroom in Töölö",
        description: "Beautifully renovated apartment within walking distance of parks, shops, and the city centre.",
        listingType: "rent",
        propertyType: "residential",
        propertySubType: "apartment",
        price: 1190,
        currency: "EUR",
        city: "Helsinki",
        address: "Runeberginkatu 40",
        postalCode: "00260",
        rooms: 2,
        bedrooms: 1,
        bathrooms: 1,
        size: 48,
        features: {
            balcony: true,
            elevator: true,
            parking: false,
            furnished: false,
            petsAllowed: true,
            sauna: false,
        },
        rentalDetails: {
            availableFrom: "2026-11-01",
            deposit: 1190,
            minimumRentalPeriod: 12,
            additionalCosts: "Water is included. Electricity is paid separately.",
        },
        image: house_image,
        images: [
            {
                id: 4,
                url: "/images/property-004.jpg",
                description: "Bright living room",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T15:00:00Z",
        updatedAt: "2026-09-06T15:00:00Z",
    },

    {
        id: 5,
        ownerId: 5,
        title: "Modern penthouse in Pasila",
        description: "Contemporary penthouse with panoramic city views and a large private terrace.",
        listingType: "sale",
        propertyType: "residential",
        propertySubType: "penthouse",
        price: 589000,
        currency: "EUR",
        city: "Helsinki",
        address: "Pasilankatu 8",
        postalCode: "00520",
        rooms: 4,
        bedrooms: 2,
        bathrooms: 2,
        size: 94,
        features: {
            balcony: true,
            elevator: true,
            parking: true,
            furnished: true,
            petsAllowed: true,
            sauna: true,
        },
        rentalDetails: {
            availableFrom: null,
            deposit: null,
            minimumRentalPeriod: null,
            additionalCosts: "Maintenance fee approximately 420 EUR/month.",
        },
        image: house_image,
        images: [
            {
                id: 5,
                url: "/images/property-005.jpg",
                description: "Penthouse terrace",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T16:00:00Z",
        updatedAt: "2026-09-06T16:00:00Z",
    },

    {
        id: 6,
        ownerId: 6,
        title: "Quiet apartment near Tapiola",
        description: "Comfortable two-bedroom apartment in a peaceful area with excellent transport connections.",
        listingType: "rent",
        propertyType: "residential",
        propertySubType: "apartment",
        price: 1450,
        currency: "EUR",
        city: "Espoo",
        address: "Itätuulenkuja 6",
        postalCode: "02100",
        rooms: 3,
        bedrooms: 2,
        bathrooms: 1,
        size: 67,
        features: {
            balcony: true,
            elevator: true,
            parking: true,
            furnished: false,
            petsAllowed: true,
            sauna: true,
        },
        rentalDetails: {
            availableFrom: "2026-10-01",
            deposit: 1450,
            minimumRentalPeriod: 12,
            additionalCosts: "Water included. Electricity paid separately.",
        },
        image: house_image,
        images: [
            {
                id: 6,
                url: "/images/property-006.jpg",
                description: "Living room",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T17:00:00Z",
        updatedAt: "2026-09-06T17:00:00Z",
    },

    {
        id: 7,
        ownerId: 7,
        title: "Traditional wooden house in Porvoo",
        description: "Charming renovated wooden house with a private garden in a peaceful historic neighborhood.",
        listingType: "sale",
        propertyType: "residential",
        propertySubType: "house",
        price: 365000,
        currency: "EUR",
        city: "Porvoo",
        address: "Jokikatu 18",
        postalCode: "06100",
        rooms: 4,
        bedrooms: 2,
        bathrooms: 1,
        size: 102,
        features: {
            balcony: false,
            elevator: false,
            parking: true,
            furnished: false,
            petsAllowed: true,
            sauna: true,
        },
        rentalDetails: {
            availableFrom: null,
            deposit: null,
            minimumRentalPeriod: null,
            additionalCosts: "Heating costs depend on consumption.",
        },
        image: house_image,

        images: [
            {
                id: 7,
                url: "/images/property-007.jpg",
                description: "Wooden house exterior",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T18:00:00Z",
        updatedAt: "2026-09-06T18:00:00Z",
    },

    {
        id: 8,
        ownerId: 8,
        title: "Affordable apartment in Vantaa",
        description: "Well-maintained apartment with convenient access to public transport and local services.",
        listingType: "rent",
        propertyType: "residential",
        propertySubType: "apartment",
        price: 980,
        currency: "EUR",
        city: "Vantaa",
        address: "Tikkurilantie 12",
        postalCode: "01300",
        rooms: 2,
        bedrooms: 1,
        bathrooms: 1,
        size: 45,
        features: {
            balcony: true,
            elevator: true,
            parking: true,
            furnished: false,
            petsAllowed: false,
            sauna: false,
        },
        rentalDetails: {
            availableFrom: "2026-10-10",
            deposit: 980,
            minimumRentalPeriod: 12,
            additionalCosts: "Water is included. Electricity is separate.",

        },
        image: house_image,
        images: [
            {
                id: 8,
                url: "/images/property-008.jpg",
                description: "Apartment living room",
                isMain: true,
            },
        ],
        status: "active",
        createdAt: "2026-09-06T19:00:00Z",
        updatedAt: "2026-09-06T19:00:00Z",
    },
];

