const express = require("express");                                                                                                                                                                                                         
const { getEstimate, getGrowth } = require("../controllers/estimationControllers");  
const { requireAuth, requireVerifiedSellerOrAgent} = require("../middleware/authMiddleware");                                                                                                                                                                
                                                                                                                                                                                                                                            
const router = express.Router();                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
router.post("/", requireAuth, requireVerifiedSellerOrAgent,  getEstimate);                                                                                                                                                                                                      
router.post("/growth", requireAuth, requireVerifiedSellerOrAgent, getGrowth);                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
module.exports = router;   