"""                                                                                                                                                                                                                                         
Combined inference service: price estimation + growth forecasting.                                                                                                                                                                          
                                                                                                                                                                                                                                            
POST /predict          -> price estimate for a property                                                                                                                                                                                     
POST /predict-growth   -> 5-year growth forecast for a postal code                                                                                                                                                                          
"""                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                            
import json                                                                                                                                                                                                                                 
import os
from math import trunc                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                            
from flask import Flask, request, jsonify                                                                                                                                                                                                   
import lightgbm as lgb                                                                                                                                                                                                                      
import numpy as np                                                                                                                                                                                                                          
import pandas as pd                                                                                                                                                                                                                         
                                                                                                                                                                                                                                            
app = Flask(__name__)                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
CURRENT_YEAR = 2026                                                                                                                                                                                                                         
HORIZON = 5                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                            
# ---------------------------------------------------------------------------                                                                                                                                                               
# Load price model + its postal code encoding                                                                                                                                                                                               
# ---------------------------------------------------------------------------                                                                                                                                                               
price_model = lgb.Booster(model_file="./utils/estimation_models/model.txt")                                                                                                                                                                                           
                                                                                                                                                                                                                                            
if not os.path.exists("./utils/estimation_models/data/postal_code_ppsm.json"):                                                                                                                                                                                             
    raise RuntimeError("postal_code_ppsm.json not found. Run: python train_model.py")                                                                                                                                                       
                                                                                                                                                                                                                                            
with open("./utils/estimation_models/data/postal_code_ppsm.json") as f:                                                                                                                                                                                                    
    ppsm_encoding = json.load(f)                                                                                                                                                                                                            
POSTAL_PPSM = ppsm_encoding["postalCodes"]                                                                                                                                                                                                  
GLOBAL_MEAN_PPSM = ppsm_encoding["globalMean"]                                                                                                                                                                                              
                                                                                                                                                                                                                                            
VALID_BUILDING_TYPES = {
    "apartment",
    "detached-house",
    "semi-detached-house",
    "terraced-house",
}                                                                                                                                                                              
                                                                                                                                                                                                                                            
# ---------------------------------------------------------------------------                                                                                                                                                               
# Load growth model + its postal code encoding + price history                                                                                                                                                                              
# ---------------------------------------------------------------------------                                                                                                                                                               
growth_model = lgb.Booster(model_file="./utils/estimation_models/model_growth.txt")                                                                                                                                                                                   
                                                                                                                                                                                                                                            
if not os.path.exists("./utils/estimation_models/data/postal_code_growth.json"):                                                                                                                                                                                           
    raise RuntimeError(                                                                                                                                                                                                                     
        "postal_code_growth.json not found. Run: python train_growth.py"                                                                                                                                                                    
    )                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
with open("./utils/estimation_models/data/postal_code_growth.json") as f:                                                                                                                                                                                                  
    growth_encoding = json.load(f)                                                                                                                                                                                                          
POSTAL_GROWTH = growth_encoding["postalCodes"]                                                                                                                                                                                              
GLOBAL_MEAN_GROWTH = growth_encoding["globalMean"]                                                                                                                                                                                          
                                                                                                                                                                                                                                            
# IMPORTANT: read postalCode as string so "05500" doesn't become 5500.                                                                                                                                                                      
history = pd.read_csv("./utils/estimation_models/data/price_growth.csv", dtype={"postalCode": str})                                                                                                                                                                   
HISTORY_MAX_YEAR = int(history["year"].max())                                                                                                                                                                                               
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
def normalize_postal(raw):                                                                                                                                                                                                                  
    """Accept "05500", 5500, "5500" etc. -> zero-padded 5-digit string."""                                                                                                                                                                  
    return str(raw).strip().zfill(5)                                                                                                                                                                                                        
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
# ---------------------------------------------------------------------------                                                                                                                                                               
# Price estimation                                                                                                                                                                                                                          
# ---------------------------------------------------------------------------                                                                                                                                                               
@app.post("/predict")                                                                                                                                                                                                                       
def predict():                                                                                                                                                                                                                              
    d = request.json                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            
    if d["buildingType"] not in VALID_BUILDING_TYPES:                                                                                                                                                                                       
        return jsonify({                                                                                                                                                                                                                    
            "error": f"Unknown buildingType '{d['buildingType']}'. "                                                                                                                                                                        
                     f"Must be one of: {sorted(VALID_BUILDING_TYPES)}"                                                                                                                                                                      
        }), 400                                                                                                                                                                                                                             
                                                                                                                                                                                                                                            
    postal = normalize_postal(d["postalCode"])                                                                                                                                                                                              
    postal_ppsm = POSTAL_PPSM.get(postal)                                                                                                                                                                                                   
    if postal_ppsm is None:                                                                                                                                                                                                                 
        postal_ppsm = GLOBAL_MEAN_PPSM                                                                                                                                                                                                      

    building_type = d["buildingType"]                                                                                                                                                                                                             
    row = pd.DataFrame([{
        "postalPpsm": postal_ppsm,
        "size": d["size"],
        "rooms": d.get("rooms"),
        "age": CURRENT_YEAR - d["buildingYear"],
        "isDetached": 1 if building_type == "detached-house" else 0,
        "isSemiDetached": 1 if building_type == "semi-detached-house" else 0,
        "isTerraced": 1 if building_type == "terraced-house" else 0,
    }])                                                                                                                                                                                                                              
    return jsonify({"estimate": (trunc(float(price_model.predict(row)[0])/1000))*1000})                                                                                                                                                                        
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
# ---------------------------------------------------------------------------                                                                                                                                                               
# Growth forecasting                                                                                                                                                                                                                        
# ---------------------------------------------------------------------------                                                                                                                                                               
def build_growth_features(postal):                                                                                                                                                                                                          
    g = history[history["postalCode"] == postal].sort_values("year").reset_index(drop=True)                                                                                                                                                 
    if g.empty:                                                                                                                                                                                                                             
        return None                                                                                                                                                                                                                         
    ppsm = g["ppsm"].values                                                                                                                                                                                                                 
    i = len(g) - 1                                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
    def past_growth(n):                                                                                                                                                                                                                     
        if i - n < 0:                                                                                                                                                                                                                       
            return np.nan                                                                                                                                                                                                                   
        return (ppsm[i] / ppsm[i - n]) ** (1 / n) - 1                                                                                                                                                                                       
                                                                                                                                                                                                                                            
    window = ppsm[max(0, i - 5): i + 1]                                                                                                                                                                                                     
    returns = np.diff(window) / window[:-1] if len(window) > 1 else np.array([0.0])                                                                                                                                                         
                                                                                                                                                                                                                                            
    postal_growth = POSTAL_GROWTH.get(postal, GLOBAL_MEAN_GROWTH)                                                                                                                                                                           
                                                                                                                                                                                                                                            
    row = pd.DataFrame([{                                                                                                                                                                                                                   
        "postalGrowth": postal_growth,                                                                                                                                                                                                      
        "ppsm": ppsm[i],                                                                                                                                                                                                                    
        "growth1y": past_growth(1),                                                                                                                                                                                                         
        "growth3y": past_growth(3),                                                                                                                                                                                                         
        "growth5y": past_growth(5),                                                                                                                                                                                                         
        "volatility5y": float(np.std(returns)) if len(returns) else 0.0,                                                                                                                                                                    
        "yearsSincePeak": int(i - np.argmax(ppsm[: i + 1])),                                                                                                                                                                                
    }])                                                                                                                                                                                                                                     
    return row, float(ppsm[i])                                                                                                                                                                                                              
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
@app.post("/predict-growth")                                                                                                                                                                                                                
def predict_growth():                                                                                                                                                                                                                       
    postal = normalize_postal(request.json["postalCode"])                                                                                                                                                                                   
    result = build_growth_features(postal)                                                                                                                                                                                                  
    if result is None:                                                                                                                                                                                                                      
        return jsonify({"error": f"No price history for postal code {postal}"}), 404                                                                                                                                                        
                                                                                                                                                                                                                                            
    row, current_ppsm = result                                                                                                                                                                                                              
    annual_growth = float(growth_model.predict(row)[0])                                                                                                                                                                                     
                                                                                                                                                                                                                                            
    forecast = []                                                                                                                                                                                                                           
    ppsm = current_ppsm                                                                                                                                                                                                                     
    for step in range(1, HORIZON + 1):                                                                                                                                                                                                      
        ppsm *= (1 + annual_growth)                                                                                                                                                                                                         
        forecast.append({"year": HISTORY_MAX_YEAR + step, "ppsm": round(ppsm)})                                                                                                                                                             
                                                                                                                                                                                                                                            
    return jsonify({                                                                                                                                                                                                                        
        "postalCode": postal,                                                                                                                                                                                                               
        "currentPpsm": round(current_ppsm),                                                                                                                                                                                                 
        "annualGrowthPct": round(annual_growth * 100, 2),                                                                                                                                                                                   
        "forecast": forecast,                                                                                                                                                                                                               
    })                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
if __name__ == "__main__":                                                                                                                                                                                                                  
    app.run(port=5001)                                                                                                                                                                                                                      
                            
